### ISSUE TITLE
oct fix tracker

### ISSUE THREAD

**Issue by haircommander** [openshift/origin-ci-tool#193]
Me and @dobbymoodge have determined oct needs some love

- image stage crio doesn't make very much sense based on the original intent of the `image_stage`. oct should be extended to support this in the operating system, and support more than {fedora,centos,rhel} in the tags (fedora_30_crio for instance)
- If we intend on using oct past Jan 1, 2020, we should probably look into extending for python3 support? Or taking the still relevant parts of oct and making a new tool that does 
- and probably more

**Comment by stevekuznetsov** [comment]
We're very close to allowing users to schedule jobs on a cluster where they can opt into being UID 0 and using nested virtualization, at which point I would really love for the CRI-O team to simply use that method instead of requiring a VM for everything, unless there is something specifically necessary about the VM. Ansible is fragile and working on oct is challenging, I'd rather see it dead.

**Comment by haircommander** [comment]
I have no objections to that. @mrunalp @umohnani8 WDYT

**Comment by stevekuznetsov** [comment]
cc @cgwalters

**Comment by cgwalters** [comment]
Right, this is https://github.com/openshift/release/issues/4892

> opt into being UID 0 and using nested virtualization

FWIW these are orthogonal things - using nested virt doesn't require uid 0, just the KVM device; and there's a general belief that exposing the KVM device to untrusted code is relatively safe.

And yeah, I think the approach I'm aiming for with the CoreOS CI would absolutely encompass the needs of crio.

**Comment by haircommander** [comment]
out of curiosity, what is the status of this @stevekuznetsov

**Comment by stevekuznetsov** [comment]
... of what?
