### ISSUE TITLE
Structured Logging

### ISSUE THREAD

**Issue by enj** [openshift/origin-ci-tool#7]
Whenever you start logging, consider using [leveldb](https://github.com/wbolster/plyvel) or [tinydb](https://github.com/msiemens/tinydb) as simple key/value storage to disk for [structlog](https://github.com/hynek/structlog) data (and perhaps add commands to search and filter).

[This](https://www.influxdata.com/benchmarking-leveldb-vs-rocksdb-vs-hyperleveldb-vs-lmdb-performance-for-influxdb/) may be of interest as well.

**Comment by stevekuznetsov** [comment]
Need to think about the schema here.

Tasks and Plays are simple:
 - name
 - location (file:line)
 - uuid
 - parent uuid (play for task, playbook for play)

Playbooks:
 - file
 - uuid

Events are not so simple:
 - task uuid
 - start time
 - stop time
 - host

However, we get an event for the start of _all_ hosts on a task, but then completion messages _per host_, so we would want to keep track of the "current" start time for a specific task uuid?

Also I'd like to get the display plugin to simply read this info from the DB and print the currently executing bits instead of doing work and responding to Ansible callbacks. So we either need to cache currently running stuff in the DB or still plug into the callback framework to get callbacks to know the uuids to search for.
